In [ ]:
import numpy as np
from scipy import integrate

# Define a simple function
def integrand(x):
    return x**2

# Compute the integral of the function
result, _ = integrate.quad(integrand, 0, 1)
print("Integral of x^2 from 0 to 1:", result)

In [ ]:
# Utilisez NumPy pour créer un grand tableau aléatoire de nombres à virgule flottante.
data = np.random.rand(1000000)
print("Data shape:", data)

In [ ]:
# importer les bibliothèques nécessaires
import pandas as pd
from scipy import integrate

In [ ]:
# Calculez la moyenne et l'écart type en utilisant à la fois NumPy et SciPy
data_moy1 = np.mean(data)
data_ecart1 = np.std(data)
print("Moyenne (NumPy):", data_moy1)
print("Écart type (NumPy):", data_ecart1)

data_moy2 = integrate.simpson(data, dx=1/1000000) / len(data)
data_ecart2 = np.sqrt(integrate.simpson((data - data_moy2) ** 2, dx=1/1000000))
print("Moyenne (SciPy):", data_moy2)
print("Écart type (SciPy):", data_ecart2)

In [ ]:
# Comparez les résultats et le temps d'exécution pour comprendre l'efficacité ou les fonctionnalités supplémentaires offertes par SciPy
data_moy1 = np.mean(data)
data_ecart1 = np.std(data)

In [ ]:
import numpy as np

daily_steps = np.random.randint(3000, 10000, size=50)

mean_np = np.mean(daily_steps)
median_np = np.median(daily_steps)
variance_np = np.var(daily_steps)
std_dev_np = np.std(daily_steps)

print(mean_scipy)

In [ ]:
import scipy.stats as stats

mean_scipy = stats.tmean(daily_steps)
median_scipy = np.median(daily_steps)  # SciPy does not have a separate median function
variance_scipy = stats.tvar(daily_steps)
std_dev_scipy = stats.tstd(daily_steps)

print(variance_scipy)

In [ ]:
skewness = stats.skew(daily_steps)
kurtosis = stats.kurtosis(daily_steps)

print(skewness)

In [ ]:
import pandas as pd
import numpy as np

# Simulating stock prices for a non-existent stock (DVLPRS)
np.random.seed(0)  # For reproducibility

# Generating 100 days of stock prices
dates = pd.date_range(start='2023-01-01', periods=100)
prices = np.random.normal(loc=100, scale=10, size=len(dates))  # Assume a mean price of 100 with a standard deviation of 10

# Creating a DataFrame
stock_data = pd.DataFrame({
    'Date': dates,
    'DVLPRS_Price': prices
})

# Displaying the first few rows of the simulated data
print(stock_data.head())

In [ ]:
# Calculez la moyenne, la médiane, la variance et l'écart type des cours boursiers
data_moy = stock_data['DVLPRS_Price'].mean()
data_median = stock_data['DVLPRS_Price'].median()
data_variance = stock_data['DVLPRS_Price'].var()
data_std_dev = stock_data['DVLPRS_Price'].std()

print("Moyenne des prix:", data_moy)
print("Médiane des prix:", data_median)
print("Variance des prix:", data_variance)
print("Écart type des prix:", data_std_dev)

Interpréter les résultats dans le contexte de l'analyse des données financières:

1. **Moyenne des prix**: La moyenne des prix boursiers donne une idée générale du niveau moyen des cours sur la période analysée. Si la moyenne est élevée, cela peut indiquer que les actions ont été généralement performantes.

2. **Médiane des prix**: La médiane est moins sensible aux valeurs extrêmes que la moyenne. Si la médiane est significativement différente de la moyenne, cela peut indiquer la présence de valeurs aberrantes ou d'une distribution asymétrique des prix.

3. **Variance des prix**: La variance mesure la dispersion des prix autour de la moyenne. Une variance élevée indique que les prix ont été très volatils, tandis qu'une variance faible suggère une stabilité relative des cours.

4. **Écart type des prix**: L'écart type est la racine carrée de la variance et fournit une mesure de la volatilité des prix. Un écart type élevé signifie que les prix ont fluctué considérablement, ce qui peut être un indicateur de risque pour les investisseurs.

In [ ]:
import numpy as np

# Sample data
group_a_scores = np.array([75, 88, 91, 83, 85])
group_b_scores = np.array([79, 90, 87, 88, 90])

# Calculate means
mean_a = np.mean(group_a_scores)
mean_b = np.mean(group_b_scores)

In [ ]:
# Calculate standard deviation
std_a = np.std(group_a_scores, ddof=1)
std_b = np.std(group_b_scores, ddof=1)

In [ ]:
from scipy.stats import ttest_ind

# Perform T-test
t_stat, p_val = ttest_ind(group_a_scores, group_b_scores)
print("Group A - Mean:", mean_a, "Std Dev:", std_a)
print("Group B - Mean:", mean_b, "Std Dev:", std_b)

In [ ]:
from scipy.stats import t

# Example: finding critical value for df = 20 and alpha = 0.05
df = 20
alpha = 0.05
critical_value = t.ppf(1 - alpha/2, df)

# Output the critical value
print("Critical Value:", critical_value)

In [ ]:
# Poisson Example
from scipy import stats
lambda_ = 3  # average number of calls per hour
poisson_dist = stats.poisson(lambda_)
print("PMF for 3 events:", poisson_dist.pmf(3))

In [ ]:
from scipy import stats

# Example: Gaussian Distribution
mu, sigma = 0, 0.1  # mean and standard deviation
gaussian_dist = stats.norm(mu, sigma)
print("PDF at x=0.5:", gaussian_dist.pdf(0.5))

In [ ]:
# Example: Binomial Distribution
n, p = 10, 0.5  # number of trials, probability of each trial
binom_dist = stats.binom(n, p)
print("PMF at 5 successes:", binom_dist.pmf(5))

In [ ]:
# Example: Poisson Distribution
lambda_ = 3  # rate
poisson_dist = stats.poisson(lambda_)
print("PMF for 3 events:", poisson_dist.pmf(3))

In [ ]:
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt

# Gaussian Distribution
mu, sigma = 0, 0.1  # mean and standard deviation
gaussian_dist = stats.norm(mu, sigma)
print("PDF at x=0.5:", gaussian_dist.pdf(0.5))

# Plotting Gaussian Distribution
x_gaussian = np.linspace(-0.5, 0.5, 100)
pdf_gaussian = gaussian_dist.pdf(x_gaussian)
plt.figure(figsize=(6, 4))
plt.plot(x_gaussian, pdf_gaussian)
plt.title('Gaussian Distribution\n$\mu=0$, $\sigma=0.1$')
plt.xlabel('x')
plt.ylabel('PDF')
plt.show()

In [ ]:
# Plotting Binomial Distribution
x_binom = np.arange(0, n+1)
pmf_binom = binom_dist.pmf(x_binom)
plt.figure(figsize=(6, 4))
plt.bar(x_binom, pmf_binom)
plt.title('Binomial Distribution\n$n=10$, $p=0.5$')
plt.xlabel('Number of Successes')
plt.ylabel('PMF')
plt.show()

In [ ]:
# Poisson Distribution
lambda_ = 3  # rate
poisson_dist = stats.poisson(lambda_)
print("PMF for 3 events:", poisson_dist.pmf(3))

# Plotting Poisson Distribution
x_poisson = np.arange(0, 10)
pmf_poisson = poisson_dist.pmf(x_poisson)
plt.figure(figsize=(6, 4))
plt.bar(x_poisson, pmf_poisson)
plt.title('Poisson Distribution\n$\lambda=3$')
plt.xlabel('Number of Events')
plt.ylabel('PMF')
plt.show()

In [ ]:
# T-test Example
group1 = stats.norm.rvs(loc=5, scale=10, size=100)
group2 = stats.norm.rvs(loc=5, scale=10, size=100)

t_statistic, p_value = stats.ttest_ind(group1, group2)
print("T-statistic:", t_statistic)
print("P-value:", p_value)

In [5]:
import numpy as np

In [ ]:
# Tableau a 1D avec le nombre 1 a 5
table_1D = np.array([1, 2 , 3 , 4 , 5])
print(table_1D)

# Tableau a 2D avec un nombre 1 à 6
table_2D = np.array([[1, 2 , 3], [ 4, 5 , 6]])
print(table_2D)



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
2.4.6


In [11]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]


In [12]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3]) 

Slice of the array: [[2 3]
 [5 6]]


In [15]:
import numpy as np

# Example array
array = np.array([[1, 2], 
                  [3, 4], 
                  [5, 6]])
print(array.shape)

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)

(3, 2)
Result of Boolean Indexing: [4 5 6]


In [16]:
import numpy as np

# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])

First element: 10
First three elements: [10 20 30]


In [17]:
# Fancy indexing (using a list of indices)
print("Select specific elements:", array[[1, 3]])

Select specific elements: [20 40]


In [21]:
import numpy as np

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


In [20]:
import numpy as np

# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:", a)
print("1D Array:", b)
print("Broadcasted Multiplication:", result)

2D Array: [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3]
Broadcasted Multiplication: [[ 1  4  9]
 [ 4 10 18]]


In [22]:
# Creating a sample array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print("Sum:", np.sum(array))

# Mean value
print("Mean:", np.mean(array))

# Minimum and Maximum
print("Min:", np.min(array), "Max:", np.max(array))

Sum: 21
Mean: 3.5
Min: 1 Max: 6
