**Exercice 1 : Création et manipulation de tableaux**

In [7]:
# Importer les bibliothèque néccessaire
import numpy as np

In [10]:
# Créez un tableau NumPy unidimensionnel contenant les nombres de 0 à 9.

matrice_1d = np.arange(0, 10)
matrice_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

------

**Exercice 2 : Conversion de type et opérations sur les tableaux**

In [11]:
#Import les bibliothèque néccessaire
import numpy as np

In [22]:
# Convertissez une liste [3.14, 2.17, 0, 1, 2]en un tableau NumPy et convertissez son type de données en entier.
list = [3.14, 2.17, 0, 1, 2]
arrays = np.array(list)

#Convertir son type de donnée en entier
array_int = np.array(arrays, dtype=int)
array_int

array([3, 2, 0, 1, 2])

-------

**Exercice 3 : Travailler avec des tableaux multidimensionnels**

In [23]:
#Importer les bibliothèque néccessaire
import numpy as np

In [26]:
# Créez un tableau NumPy 3x3 avec des valeurs allant de 1 à 9.
array_3D = np.arange(1, 10).reshape(3, 3)
array_3D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

-------

**Exercice 4 : Création d'un tableau multidimensionnel avec des nombres aléatoires**

In [29]:
#Importer les bibliothèque néccessaire
import numpy as np

In [30]:
# Créez un tableau NumPy 2D de forme (4, 5) rempli de nombres aléatoires

array_2d = np.random.rand(4, 5)
array_2d

array([[0.61748629, 0.54696791, 0.41775373, 0.02077585, 0.09953816],
       [0.50208954, 0.46223556, 0.18990033, 0.86190489, 0.71160483],
       [0.72655336, 0.41719065, 0.23833887, 0.48860696, 0.60373753],
       [0.59372274, 0.83158681, 0.16415821, 0.47169138, 0.1475717 ]])

----------

**Exercice 5 : Indexation des tableaux**

In [31]:
# Importer les biblithèque néccesaire
import numpy as np

In [39]:
# Sélectionnez la deuxième ligne d'un tableau NumPy 2D donné
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array_row2 = array[1:]
array_row2

array([[20, 21, 22, 23, 24],
       [21, 22, 23, 22, 22]])

----

**Exercice 6 : Inversion des éléments**

In [40]:
# Importer les bibliothèqus néccessaire
import numpy as np

In [53]:
# Inverser l'ordre des éléments d'un tableau NumPy 1D donné (le premier élément devient le dernier).
array_1D = np.arange(0, 10)
array_1D

array_inverse = array_1D[::-1]
array_inverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

---------

**Exercice 7 : Matrice identité**

In [54]:
# Import les bibliothèque néccessaire
import numpy as np

In [57]:
# Créez une matrice identité 4x4 à l'aide de NumPy.
array_ident = np.eye(4)
array_ident

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

--------

**Exercice 8 : Fonctions agrégées simples**

In [58]:
# Import les bibliothèque néccessaire
import numpy as np

In [67]:
# Trouvez la somme et la moyenne d'un tableau 1D donné.
list_1d = np.arange(1, 11)

# Somme de la liste
sum_list = np.sum(list_1d)
# La moynenne de la liste
moy_list = np.mean(list_1d)

print(f"Sum: {sum_list}, Average: {moy_list}")

Sum: 55, Average: 5.5


-----------

**Exercice 9 : Créer un tableau et modifier sa structure**

In [68]:
# Importer les bibliothèque néccessaire
import numpy as np

In [71]:
# Créez un tableau NumPy avec des éléments de 1 à 20 ; puis remodelez-le en une matrice 4x5.
array_ID = np.arange(1, 21)

# Convertir en matrice 4x5
array_mat = array_ID.reshape(4, 5)
array_mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

----------

**Exercice 10 : Sélection conditionnelle des valeurs**

In [72]:
# Importer les bibliotèque néccessaire
import numpy as np

In [77]:
# Extraire tous les nombres impairs d'un tableau NumPy donné.

tab = np.arange(1, 11)

# Extraire les nombres impairs
impair = tab[tab %2 != 0]
impair

array([1, 3, 5, 7, 9])